### ISSUE TITLE
Videos Are Missing

### ISSUE THREAD

**Issue by impulsecorp** [wyndwarrior/imitation_from_observation#1]
In your code, all of the mp4 videos have a path to load from your hard drive, and don't seem to be part of your GitHub. It would be good if you could include some sample videos to use with your code.

**Comment by hcwang95** [comment]
We have the same problem. In the ipython notebook, we cannot load the sequence of images. Could you help us by upload those videos?

**Comment by wyndwarrior** [comment]
The videos are large and hard to host, you should be able to regenerate them using the expert_*.pkl policies.
